package io.ruin.model.content.upgrade;

import io.ruin.cache.ItemID;
import io.ruin.model.item.Item;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

/*
 * @project Kronos
 * @author Patrity - https://github.com/Patrity
 * Created on - 6/30/2020
 */

@Getter @RequiredArgsConstructor
public enum ScrapableItems {

    ABYSSAL_WHIP(ItemID.ABYSSAL_WHIP, 250000),
    ABYSSAL_TENTATCLE(ItemID.ABYSSAL_TENTACLE, 400000),
    ELDER_MAUL(ItemID.ELDER_MAUL, 500000),
    TWISTED_BOW(ItemID.TWISTED_BOW, 1000000),
    DINHS_BULWARK(ItemID.DINHS_BULWARK, 400000),
    ACESTRAL_HAT(ItemID.ANCESTRAL_HAT, 400000),
    ANCESTRAL_TOP(ItemID.ANCESTRAL_ROBE_TOP, 400000),
    ANCESTRAL_BOTTOMS(ItemID.ANCESTRAL_ROBE_BOTTOM, 400000),
    CHAINMACE(ItemID.VIGGORAS_CHAINMACE, 250000),
    CRAWS_BOW(ItemID.CRAWS_BOW, 125000),
    DRAGONFIRE_SHIELD(ItemID.DRAGONFIRE_SHIELD, 125000),
    BLOW_PIPE(ItemID.TOXIC_BLOWPIPE_EMPTY, 450000),

    /*
     * GWD Items
     */
    BANDOS_CHEST(ItemID.BANDOS_CHESTPLATE, 300000),
    BANDOS_TASSETS(ItemID.BANDOS_TASSETS, 300000),
    BANDOS_BOOTS(ItemID.BANDOS_BOOTS, 75000),

    ARMADYL_HELM(ItemID.ARMADYL_HELMET, 75000),
    ARMADYL_CHEST(ItemID.ARMADYL_CHESTPLATE, 300000),
    ARMADYL_SKIRT(ItemID.ARMADYL_CHAINSKIRT, 300000),

    SARA_GODSWORD(ItemID.SARADOMIN_GODSWORD, 450000),
    BANDOS_GODSWORD(ItemID.BANDOS_GODSWORD, 450000),
    ZAMMY_GODSWORD(ItemID.ZAMORAK_GODSWORD, 450000),
    ARMA_GODSWORD(ItemID.ARMADYL_GODSWORD, 450000),

    STAFF_OF_THE_DEAD(ItemID.STAFF_OF_THE_DEAD, 300000),

    /*
     * PVP Gear
     */
    STATIUS_HELM(ItemID.STATIUSS_FULL_HELM, 300000),
    STATIUS_CHEST(ItemID.STATIUSS_PLATEBODY, 300000),
    STATIUS_LEGS(ItemID.STATIUSS_PLATELEGS, 300000),
    STATIUS_HAMMER(ItemID.STATIUSS_WARHAMMER, 450000),

    VESTA_CHEST(ItemID.VESTAS_CHAINBODY, 300000),
    VESTA_LEGS(ItemID.VESTAS_PLATESKIRT, 300000),
    VESTA_LONGSWORD(ItemID.VESTAS_LONGSWORD, 450000),
    VESTA_SPEAR(ItemID.VESTAS_SPEAR, 450000),

    ZURIEL_HOOD(ItemID.ZURIELS_HOOD, 300000),
    ZURIEL_CHEST(ItemID.ZURIELS_ROBE_TOP, 300000),
    ZURIEL_BOTTOM(ItemID.ZURIELS_ROBE_BOTTOM, 300000),
    ZURIEL_STAFF(ItemID.ZURIELS_STAFF, 450000),

    MORRIGAN_HELM(ItemID.MORRIGANS_COIF, 300000),
    MORRIGAN_TOP(ItemID.MORRIGANS_LEATHER_BODY, 300000),
    MORRIGAN_LEGS(ItemID.MORRIGANS_LEATHER_CHAPS, 300000),
    MORRIGAN_AXE(ItemID.MORRIGANS_THROWING_AXE, 1500),
    MORRIGAN_JAVELIN(ItemID.MORRIGANS_JAVELIN, 1500),

    /*
     * BARROWS
     */
    AHRIM_SKIRT(ItemID.AHRIMS_ROBESKIRT, 50000),
    AHRIM_CHEST(ItemID.AHRIMS_ROBETOP, 50000),
    AHRIM_HOOD(ItemID.AHRIMS_HOOD, 50000),
    AHRIM_STAFF(ItemID.AHRIMS_STAFF, 50000),
    KARILS_COIF(ItemID.KARILS_COIF, 50000),
    KARILS_TOP(ItemID.KARILS_LEATHERTOP, 50000),
    KARILS_SKIRT(ItemID.KARILS_LEATHERSKIRT, 50000),
    KARILS_BOW(ItemID.KARILS_CROSSBOW, 50000),
    DHAROKS_HELM(ItemID.DHAROKS_HELM, 50000),
    DHAROKS_CHEST(ItemID.DHAROKS_PLATEBODY, 50000),
    DHAROKS_LEGS(ItemID.DHAROKS_PLATELEGS, 50000),
    DHAROKS_AXE(ItemID.DHAROKS_GREATAXE, 50000),
    GUTHANS_HELM(ItemID.GUTHANS_HELM, 50000),
    GUTHANS_CHEST(ItemID.GUTHANS_PLATEBODY, 50000),
    GUTHANS_SKIRT(ItemID.GUTHANS_CHAINSKIRT, 50000),
    GUTHANS_SPEAR(ItemID.GUTHANS_WARSPEAR, 50000),
    TORAGS_HELM(ItemID.TORAGS_HELM, 50000),
    TORAGS_CHEST(ItemID.TORAGS_PLATEBODY, 50000),
    TORAGS_LEGS(ItemID.TORAGS_PLATELEGS, 50000),
    TORAGS_HAMMERS(ItemID.TORAGS_HAMMERS, 50000),
    VERACS_HELM(ItemID.VERACS_HELM, 50000),
    VERACS_CHEST(ItemID.VERACS_BRASSARD, 50000),
    VERACS_SKIRT(ItemID.VERACS_PLATESKIRT, 50000),
    VERACS_FLAIL(ItemID.VERACS_FLAIL, 50000),

    ;

    private final int id, scrap;

}
