package io.ruin.model.skills.construction;

import static io.ruin.model.skills.construction.Buildable.*;

public enum Hotspot {
    /**
     * Empty hotspot... this is really awkward but yeah it needs to exist in some places for house viewer :(
     *
     */
    EMPTY(-1),
    /**
     * Garden
     */
    CENTERPIECE(15361, EXIT_PORTAL, DECORATIVE_ROCK, POND, IMP_STATUE, DUNGEON_ENTRANCE),
    BIG_TREE(15362, BIG_DEAD_TREE, BIG_NICE_TREE, BIG_OAK_TREE, BIG_WILLOW_TREE, BIG_MAPLE_TREE, BIG_YEW_TREE, BIG_MAGIC_TREE),
    SMALL_TREE(15363, SMALL_DEAD_TREE, SMALL_NICE_TREE, SMALL_OAK_TREE, SMALL_WILLOW_TREE, SMALL_MAPLE_TREE, SMALL_YEW_TREE, SMALL_MAGIC_TREE),
    BIG_PLANT_1(15364, FERN, BUSH, TALL_PLANT),
    BIG_PLANT_2(15365, SHORT_PLANT, LARGE_LEAF_BUSH, HUGE_PLANT),
    SMALL_PLANT_1(15366, PLANT, SMALLER_FERN, SMALL_FERN),
    SMALL_PLANT_2(15367, DOCK_LEAF, THISTLE, REEDS),
    GARDEN_TIP_JAR(29119, TIP_JAR),
    /**
     * Parlour
     */
    CHAIR_1(4515, PARLOUR_CHAIRS),
    CHAIR_2(4516, PARLOUR_CHAIRS),
    CHAIR_3(4517, PARLOUR_CHAIRS),
    RUG(new int[]{4518, 4519, 4520}, RUGS),
    BOOKCASE(4521, BOOKCASES),
    FIREPLACE(4523, FIREPLACES),
    CURTAINS(4524, CURTAIN),

    /**
     * Kitchen
     */
    STOVE(15398, FIREPIT, FIREPIT_WITH_HOOK, FIREPIT_WITH_POT, SMALL_OVEN, LARGE_OVEN, STEEL_RANGE, FANCY_RANGE),
    SHELVES(new int[]{15399, 15400}, WOODEN_SHELVES_1, WOODEN_SHELVES_2, WOODEN_SHELVES_3, OAK_SHELVES_1, OAK_SHELVES_2, TEAK_SHELVES_1, TEAK_SHELVES_2),
    BARREL(15401, BEER_BARREL, CIDER_BARREL, ASGARNIAN_ALE_BARREL, GREENMANS_ALE_BARREL, DRAGON_BITTER_BARREL, CHEFS_DELIGHT_BARREL),
    CAT_BASKET(15402, CAT_BLANKET, Buildable.CAT_BASKET, CAT_CUSHIONED_BASKET),
    LARDER(15403, WOODEN_LARDER, OAK_LARDER, TEAK_LARDER),
    SINK(15404, PUMP_AND_DRAIN, PUMP_AND_TUB, Buildable.SINK),
    KITCHEN_TABLE(15405, WOODEN_KITCHEN_TABLE, OAK_KITCHEN_TABLE, TEAK_KITCHEN_TABLE),

    /**
     * Dining room
     */
    DINING_TABLE(15298, WOOD_DINING_TABLE, OAK_DINING_TABLE, CARVED_OAK_TABLE, TEAK_DINING_TABLE, CARVED_TEAK_TABLE, MAHOGANY_DINING_TABLE, OPULENT_DINING_TABLE),
    SEATING_SPACE_1(15299, WOODEN_BENCH, OAK_BENCH, CARVED_OAK_BENCH, TEAK_BENCH, CARVED_TEAK_BENCH, MAHOGANY_BENCH, GILDED_BENCH),
    SEATING_SPACE_2(15300, WOODEN_BENCH, OAK_BENCH, CARVED_OAK_BENCH, TEAK_BENCH, CARVED_TEAK_BENCH, MAHOGANY_BENCH, GILDED_BENCH),
    DINING_ROOM_FIREPLACE(15301, FIREPLACES),
    DINING_ROOM_CURTAINS(15302, CURTAIN),
    WALL_DECORATION(15303, OAK_DECORATION, TEAK_DECORATION, GILDED_DECORATION),
    BELL_PULL(15304, ROPE_BELL_PULL, Buildable.BELL_PULL, POSH_BELL_PULL),

    /**
     * Workshop
     */
    WORKBENCH(new int[]{15439, 15440}, WOODEN_WORKBENCH, OAK_WORKBENCH, STEEL_FRAMED_WORKBENCH, BENCH_WITH_VICE, BENCH_WITH_LATHE),
    CRAFTING_TABLE(new int[] {15441, 15442}, CRAFTING_TABLE_1, CRAFTING_TABLE_2, CRAFTING_TABLE_3, CRAFTING_TABLE_4),
    TOOLS(new int[] {15443, 15444, 15445, 15446, 15447}, TOOL_STORE_1, TOOL_STORE_2, TOOL_STORE_3, TOOL_STORE_4, TOOL_STORE_5),
    REPAIR_SPACE(15448, REPAIR_BENCH, WHETSTONE, ARMOUR_STAND),
    HERALDRY_STAND(15450, PLUMING_STAND, SHIELD_EASEL, BANNER_EASEL),

    /**
     * Bedroom
     */
    BED(15260, WOODEN_BED, OAK_BED, LARGE_OAK_BED, TEAK_BED, LARGE_TEAK_BED, FOUR_POSTER_BED, GILDED_FOUR_POSTER_BED),
    WARDROBE(15261, SHOE_BOX, OAK_DRAWERS, OAK_WARDROBE, TEAK_DRAWERS, TEAK_WARDROBE, MAHOGANY_WARDROBE, GILDED_WARDROBE),
    DRESSER(15262, SHAVING_STAND, OAK_SHAVING_STAND, OAK_DRESSER, TEAK_DRESSER, FANCY_TEAK_DRESSER, MAHOGANY_DRESSER, GILDED_DRESSER),
    BEDROOM_CURTAINS(15263, CURTAIN),
    BEDROOM_RUG(new int[] {15264, 15265, 15266}, RUGS),
    BEDROOM_FIREPLACE(15267, FIREPLACES),
    BEDROOM_CORNER(15268, OAK_CLOCK, TEAK_CLOCK, GILDED_CLOCK, SERVANTS_MONEYBAG),

    /**
     * Skill hall
     */
    SKILL_HALL_STAIRS_UP(new int[]{
            15380, // actual stairs - keep this in the same index as the stairs in down hall!!!!!!
            15390,
            15377, 15378, 15379, // rugs!
    }, Buildable.HALL_STAIRS_UP),
    SKILL_HALL_STAIRS_DOWN(new int[]{
            15381, // actual stairs
            15391,
            15377, 15378, 15379, // rugs!
    }, Buildable.HALL_STAIRS_DOWN),
    CW_ARMOUR_STAND(15385, CW_ARMOUR_1, CW_ARMOUR_2, CW_ARMOUR_3),
    METAL_ARMOUR_STAND(15384, MITHRIL_ARMOUR, ADAMANTITE_ARMOUR, RUNITE_ARMOUR),
    HEAD_TROPHY(15382, CRAWLING_HAND, COCKATRICE_HEAD, BASILISK_HEAD, KURASK_HEAD, ABYSSAL_DEMON_HEAD, KBD_HEADS, KALPHITE_QUEEN_HEAD, VORKATH_HEAD),
    RUNE_CASE(15386, RUNE_CASE_1, RUNE_CASE_2, RUNE_CASE_3),
    FISHING_TROPHY(15383, MOUNTED_BASS, MOUNTED_SWORDFISH, MOUNTED_SHARK),

    /**
     * Games room
     */
    GAME(15342, JESTER, TREASURE_HUNT, HANGMAN),
    PRIZE_CHEST(15343, OAK_PRIZE_CHEST, TEAK_PRIZE_CHEST, MAHOGANY_PRIZE_CHEST),
    ATTACK_STONE(15344, CLAY_ATTACK_STONE, LIMESTONE_ATTACK_STONE, MARBLE_ATTACK_STONE),
    ELEMENTAL_BALANCE(15345, LESSER_MAGICAL_BALANCE, MEDIUM_MAGICAL_BALANCE, GREATER_MAGICAL_BALANCE),
    RANGING_GAME(15346, HOOP_AND_STICK, DARTBOARD, ARCHERY_TARGET),

    /**
     * Combat room
     */
    COMBAT_RING(new int[] {15277, 15278, 15279, 15280, 15281, 15282, 15283, 15284, 15285, 15286, 15287, 15288, 15289, 15290, 15291, 15292, 15293, 15294, 15295},
            BOXING_RING, FENCING_RING, Buildable.COMBAT_RING, RANGING_PEDESTALS, BALANCE_BEAM),
    RACK(15296, GLOVE_RACK, WEAPONS_RACK, EXTRA_WEAPONS_RACK),
    COMBAT_ROOM_DECORATION(15297, OAK_DECORATION, TEAK_DECORATION, GILDED_DECORATION),
    COMBAT_DUMMY(29335, Buildable.COMBAT_DUMMY, UNDEAD_COMBAT_DUMMY),

    /**
     * Quest Hall
     */
    QUEST_HALL_STAIRS_UP(new int[]{
            15380,
            15390, // actual stairs - keep this in the same index as the stairs in down hall!!!!!!
            15388, 15387, // rugs!
    }, Buildable.HALL_STAIRS_UP),
    QUEST_HALL_STAIRS_DOWN(new int[]{
            15381,
            15391, // stairs
            15388, 15387,  // rugs
    }, Buildable.HALL_STAIRS_DOWN),
    PORTRAIT(15392, KING_ARTHUR_PORTRAIT, ELENA_PORTRAIT, GIANT_DWARF_PORTRAIT, MISCELLANIANS_PORTRAIT),
    LANDSCAPE(15393, LUMBRIDGE_LANDSCAPE, DESERT_LANDSCAPE, MORYTANIA_LANDSCAPE, KARAMJA_LANDSCAPE, ISAFDAR_LANDSCAPE),
    GUILD_TROPHY(15394, MOUNTED_ANTI_DRAGON_SHIELD, MOUNTED_AMULET_OF_GLORY, MOUNTED_LEGENDS_CAPE, MOUNTED_MYTHICAL_CAPE),
    MOUNTED_SWORD(15395, MOUNTED_SILVERLIGHT, MOUNTED_EXCALIBUR, MOUNTED_DARKLIGHT),
    MAP(15396, SMALL_MAP, MEDIUM_MAP, LARGE_MAP),
    QUEST_HALL_BOOKCASE(15397, BOOKCASES),

    /**
     * Menagerie
     */
    PET_HOUSE(26296, OAK_HOUSE, TEAK_HOUSE, MAHOGANY_HOUSE, CONSECRATED_HOUSE, DESECRATED_HOUSE, NATURE_HOUSE),
    HABITAT(new int[]{26833, 26839, 26845, 26851}, GRASSLAND_HABITAT, FOREST_HABITAT, DESERT_HABITAT, POLAR_HABITAT, VOLCANIC_HABITAT),
    SCRATCHING_POST(26857, OAK_SCRATCHING_POST, TEAK_SCRATCHING_POST, MAHOGANY_SCRATCHING_POST),
    ARENA(new int[]{26861, 26865}, SIMPLE_ARENA, ADVANCED_ARENA, GLORIOUS_ARENA),
    PET_LIST(26867, Buildable.PET_LIST),
    PET_FEEDER(26869, OAK_FEEDER, TEAK_FEEDER, MAHOGANY_FEEDER),

    /**
     * Study
     */
    LECTERN(15420, OAK_LECTERN, EAGLE_LECTERN, DEMON_LECTERN, TEAK_EAGLE_LECTERN, TEAK_DEMON_LECTERN, MAHOGANY_EAGLE_LECTERN, MAHOGANY_DEMON_LECTERN),
    GLOBE(15421, Buildable.GLOBE, ORNAMENTAL_GLOBE, LUNAR_GLOBE, CELESTIAL_GLOBE, ARMILLIARY_SPHERE, SMALL_ORRERY, LARGE_ORRERY),
    CRYSTAL_BALL(15422, Buildable.CRYSTAL_BALL, ELEMENTAL_SPHERE, CRYSTAL_OF_POWER),
    WALL_CHART(15423, ALCHEMICAL_CHART, ASTRONOMICAL_CHART, INFERNAL_CHART),
    TELESCOPE(15424, WOODEN_TELESCOPE, TEAK_TELESCOPE, MAHOGANY_TELESCOPE),
    STUDY_BOOKCASES(15425, BOOKCASES),

    /**
     * Costume room
     */
    CAPE_RACK(18810, OAK_CAPE_RACK, TEAK_CAPE_RACK, MAHOGANY_CAPE_RACK, GILDED_CAPE_RACK, MARBLE_CAPE_RACK, MAGICAL_CAPE_RACK),
    MAGIC_WARDROBE(18811, OAK_MAGIC_WARDROBE, CARVED_OAK_MAGIC_WARDROBE, TEAK_MAGIC_WARDROBE, CARVED_TEAK_MAGIC_WARDROBE, MAHOGANY_MAGIC_WARDROBE, GILDED_MAGIC_WARDROBE, MARBLE_MAGIC_WARDROBE),
    TOY_BOX(18812, OAK_TOY_BOX, TEAK_TOY_BOX, MAHOGANY_TOY_BOX),
    TREASURE_CHEST(18813, OAK_TREASURE_CHEST, TEAK_TREASURE_CHEST, MAHOGANY_TREASURE_CHEST),
    FANCY_DRESS_BOX(18814, OAK_FANCY_DRESS_BOX, TEAK_FANCY_DRESS_BOX, MAHOGANY_FANCY_DRESS_BOX),
    ARMOUR_CASE(18815, OAK_ARMOUR_CASE, TEAK_ARMOUR_CASE, MAHOGANY_ARMOUR_CASE),

    /**
     * Chapel
     */
    ICON(15269, SARADOMIN_SYMBOL, ZAMORAK_SYMBOL, GUTHIX_SYMBOL, SARADOMIN_ICON, ZAMORAK_ICON, GUTHIX_ICON, BOB_ICON),
    ALTAR(15270, OAK_ALTAR, TEAK_ALTAR, CLOTH_ALTAR, MAHOGANY_ALTAR, LIMESTONE_ALTAR, MARBLE_ALTAR, GILDED_ALTAR),
    LAMP(15271, STEEL_TORCHES, WOODEN_TORCHES, STEEL_CANDLESTICKS, GOLD_CANDLESTICKS, INCENSE_BURNER, MAHOGANY_BURNER, MARBLE_BURNER),
    WINDOW(new int[]{13733, 13728, 13732, 13729, 13730, 13731, 27070}, SHUTTERED_WINDOWS, DECORATIVE_WINDOWS, STAINED_GLASS),
    CHAPEL_RUG(new int[]{15272, 15273, 15274}, RUGS),
    STATUE(15275, SMALL_STATUE, MEDIUM_STATUE, LARGE_STATUE),
    MUSICAL(15276, WINDCHIMES, BELLS, ORGAN),

    /**
     * Portal chamber
     */
    PORTAL_1(15406, TEAK_PORTAL_FRAME, MAHOGANY_PORTAL_FRAME, MARBLE_PORTAL_FRAME),
    PORTAL_2(15407, TEAK_PORTAL_FRAME, MAHOGANY_PORTAL_FRAME, MARBLE_PORTAL_FRAME),
    PORTAL_3(15408, TEAK_PORTAL_FRAME, MAHOGANY_PORTAL_FRAME, MARBLE_PORTAL_FRAME),
    TELEPORT_FOCUS(15409, Buildable.TELEPORT_FOCUS, GREATER_TELEPORT_FOCUS, SCRYING_POOL),

    /**
     * Formal garden
     */
    FORMAL_GARDEN_CENTERPIECE(15368, EXIT_PORTAL, GAZEBO, DUNGEON_ENTRANCE, SMALL_FOUNTAIN, LARGE_FOUNTAIN, POSH_FOUNTAIN),
    FENCING(15369, BOUNDARY_STONES, WOODEN_FENCE, STONE_WALL, IRON_RAILINGS, PICKET_FENCE, GARDEN_FENCE, MARBLE_WALL),
    HEDGING(new int[]{15371, 15372, 15370}, THORNY_HEDGE, NICE_HEDGE, SMALL_BOX_HEDGE, TOPIARY_HEDGE, FANCY_HEDGE, TALL_FANCY_HEDGE, TALL_BOX_HEDGE),
    FORMAL_BIG_PLANT(15373, SUNFLOWER, MARIGOLDS, ROSES),
    FORMAL_BIG_PLANT_2(15374, ROSEMARY, DAFFODILS, BLUEBELLS),
    FORMAL_SMALL_PLANT(15375, SMALL_SUNFLOWER, SMALL_MARIGOLDS, SMALL_ROSES),
    FORMAL_SMALL_PLANT_2(15376, SMALL_ROSEMARY, SMALL_DAFFODILS, SMALL_BLUEBELLS),

    /**
     * Throne room
     */
    THRONE(15426, OAK_THRONE, TEAK_THRONE, MAHOGANY_THRONE, GILDED_THRONE, SKELETON_THRONE, CRYSTAL_THRONE, DEMONIC_THRONE),
    FLOOR_SPACE(new int[]{15427, 15428, 15429, 15430, 15431, 15432, 27071}, FLOOR_DECORATION, STEEL_CAGE_TRAP, TRAP_TRAPDOOR, LESSER_MAGIC_CAGE, GREATER_MAGIC_CAGE),
    THRONE_ROOM_WALL_DECORATION(15434, OAK_DECORATION, TEAK_DECORATION, GILDED_DECORATION, ROUND_SHIELD, SQUARE_SHIELD, KITE_SHIELD),
    LEVER(15435, OAK_LEVER, TEAK_LEVER, MAHOGANY_LEVER),
    THRONE_ROOM_SEATING_SPACE_1(15436, CARVED_TEAK_BENCH_2, MAHOGANY_BENCH_2, GILDED_BENCH_2),
    THRONE_ROOM_SEATING_SPACE_2(15437, CARVED_TEAK_BENCH_2, MAHOGANY_BENCH_2, GILDED_BENCH_2),
    TRAPDOOR(15438, OAK_TRAPDOOR, TEAK_TRAPDOOR, MAHOGANY_TRAPDOOR),

    /**
     * Oubliette
     */
    OUBLIETTE_FLOOR_SPACE(new int[]{15347, 15348, 15349, 15350, 15351}, SPIKES, TENTACLE_POOL, FLAME_PIT, ROCNAR),
    PRISON(new int[]{15352, 15353}, OAK_CAGE, OAK_AND_STEEL_CAGE, STEEL_CAGE, SPIKED_CAGE, BONE_CAGE),
    OUBLIETTE_GUARD(15354, SKELETON_GUARD, GUARD_DOG, HOBGOBLIN, BABY_RED_DRAGON, HUGE_SPIDER, TROLL_GUARD, HELLHOUND),
    LIGHTING(15355, DUNGEON_LIGHTINGS),
    LADDER(15356, OAK_LADDER, TEAK_LADDER, MAHOGANY_LADDER),
    DECORATION(15331, DUNGEON_DECORATIONS),

    /**
     * Superior garden
     */
    TELEPORT_SPACE(29120, SPIRIT_TREE, FAIRY_RING, SPIRIT_TREE_AND_FAIRY_RING, OBELISK),
    TOPIARY_SPACE(29121, TOPIARY_BUSH),
    POOL_SPACE(29122, RESTORATION_POOL, REVITALISATION_POOL, REJUVENATION_POOL, FANCY_REJUVENATION_POOL, ORNATE_REJUVENATION_POOL),
    THEME_SPACE(new int[]{29126, 29127, 29128, 29129, 29125, 29124, 29123, 29130}, ZEN_THEME, OTHERWORLDLY_THEME, VOLCANIC_THEME),
    FENCE_SPACE(new int[]{29131, 29132, 29133}, REDWOOD_FENCE, MARBLE_WALL, OBSIDIAN_FENCE),
    GARDEN_BENCH_1(new int[]{29136, 29137}, TEAK_GARDEN_BENCH, GNOME_BENCH, MARBLE_BENCH, OBSIDIAN_BENCH),
    GARDEN_BENCH_2(new int[]{29138, 29139}, TEAK_GARDEN_BENCH, GNOME_BENCH, MARBLE_BENCH, OBSIDIAN_BENCH),

    /**
     * Dungeon
     */
    DUNGEON_GUARD(15323, GUARDS),
    DUNGEON_TRAP_1(15324, DUNGEON_TRAPS),
    DUNGEON_TRAP_2(15325, DUNGEON_TRAPS),
    DUNGEON_DOOR_1(new int[]{15326, 15327}, DUNGEON_DOORS),
    DUNGEON_DOOR_2(new int[]{15328, 15329}, DUNGEON_DOORS),
    DUNGEON_LIGHTING(15330, DUNGEON_LIGHTINGS),
    DUNGEON_DECORATION(15331, DUNGEON_DECORATIONS),

    DUNGEON_STAIRS_GUARD_1(15336, GUARDS),
    DUNGEON_STAIRS_GUARD_2(15337, GUARDS),
    DUNGEON_STAIRS(new int[]{
            15380,
            15390, // stairs
            15377, 15378, 15379 // rugs!
    }, Buildable.HALL_STAIRS_UP),

    TREASURE(15256, WOODEN_CRATE, OAK_CHEST, TEAK_CHEST, MAHOGANY_CHEST, MAGIC_CHEST),
    TREASURE_BOSS(15257, DEMON, KALPHITE_SOLDIER, TOK_XIL, DAGANNOTH, STEEL_DRAGON, RUNE_DRAGON),
    TREASURE_ROOM_DECORATION(15259, ROUND_SHIELD, SQUARE_SHIELD, KITE_SHIELD),

    /**
     * Achievement gallery
     */
    SPELLBOOK_ALTAR(29140, ANCIENT_ALTAR, LUNAR_ALTAR, DARK_ALTAR),
    ADVENTURE_LOG(29141, MAHOGANY_ADVENTURE_LOG, GILDED_ADVENTURE_LOG, MARBLE_ADVENTURE_LOG),
    JEWELLERY_BOX(29142, BASIC_JEWELLERY_BOX, FANCY_JEWELLERY_BOX, ORNATE_JEWELLERY_BOX),
    BOSS_LAIR_DISPLAY(29143, BOSS_DISPLAY),
    DISPLAY(29144, MOUNTED_EMBLEM, MOUNTED_COINS, CAPE_HANGER),
    QUEST_LIST(29145, Buildable.QUEST_LIST);

    Hotspot(int[] hotspotIds, Buildable... buildables) {
        this.hotspotIds = hotspotIds;
        this.buildables = buildables;
    }

    Hotspot(int hotspotId, Buildable... buildables) {
        this(new int[]{hotspotId}, buildables);
    }


    private int[] hotspotIds;

    private Buildable[] buildables;

    public Buildable[] getBuildables() {
        return buildables;
    }

    public int[] getHotspotIds() {
        return hotspotIds;
    }



}
